
spring:
  main:
    banner-mode: console  
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      max-lifetime: 1800000 
      idle-timeout: 600000
      auto-commit: false
#      connection-test-query: SELECT 1
      pool-name: hikari_dspool
      connection-timeout: 10000
      initialization-fail-timeout: 10000
      leak-detection-threshold: 30000
#      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/testdb?useSSL=false
      username: '{cipher}3d6a7c14e4ade59dbbd61837858fa8e985b7da4b3d254cf291b11e76740f8861'
      password: 
    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
      hibernate.show_sql: true
#  jackson:
#    serialization:
#      fail-on-empty-beans: false

