
spring:
  main:
    banner-mode: off  
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      max-lifetime: 1800000 
      idle-timeout: 600000
      auto-commit: false
      pool-name: hikari_dspool
      connection-timeout: 10000
      initialization-fail-timeout: 10000
      leak-detection-threshold: 30000
      jdbc-url: jdbc:mysql://localhost:3306/proddb?useSSL=false
      username: root
      password: 
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
      hibernate.show_sql: true
#  jackson:
#    serialization:
#      fail-on-empty-beans: false

